### ISSUE TITLE
About applying mask in random_label.py

### ISSUE THREAD

**Issue by TianyunYoung** [OPTML-Group/Unlearn-Saliency#15]
I find something strange in [random_label.py](https://github.com/OPTML-Group/Unlearn-Saliency/blob/master/SD/train-scripts/random_label.py). As seen on line 133, this line is for select those parameters that have gradient and in the parameters that are optimized. However, for the condition ``n in parameters``, ``n`` is a string, and ``parameters`` is a list of weights, rather than a list of names. So ``n in paramters`` will always be False, which makes the mask not applied. Is that true? Or I miss something.

![8991715569483_ pic](https://github.com/OPTML-Group/Unlearn-Saliency/assets/22547971/2d955247-844d-4f21-af28-7bf1ccfde87b)

**Comment by TianyunYoung** [comment]
BTW, there is a bug in [nsfw_removal.py](https://github.com/OPTML-Group/Unlearn-Saliency/blob/master/SD/train-scripts/nsfw_removal.py) . The type of ``lr`` should be float, rather than int.
![9001715572082_ pic](https://github.com/OPTML-Group/Unlearn-Saliency/assets/22547971/21e089c7-cef9-4211-b2a7-94032f060bbe)

**Comment by a-F1** [comment]
Thank you for your attention and support towards our work, as well as for bringing this issue to our notice. We sincerely apologize for any misunderstanding caused by the oversight during the code cleanup process. Rest assured, we have promptly rectified the bug.

If you have any further inquiries or require additional assistance, please feel free to reach out to us.

**Comment by TianyunYoung** [comment]
I got it. Thanks for your prompt clarification.
